// Generated by gencpp from file afnan/wordcount.msg
// DO NOT EDIT!


#ifndef AFNAN_MESSAGE_WORDCOUNT_H
#define AFNAN_MESSAGE_WORDCOUNT_H

#include <ros/service_traits.h>


#include <afnan/wordcountRequest.h>
#include <afnan/wordcountResponse.h>


namespace afnan
{

struct wordcount
{

typedef wordcountRequest Request;
typedef wordcountResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct wordcount
} // namespace afnan


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::afnan::wordcount > {
  static const char* value()
  {
    return "b4834320f090e9235da913886638fb4e";
  }

  static const char* value(const ::afnan::wordcount&) { return value(); }
};

template<>
struct DataType< ::afnan::wordcount > {
  static const char* value()
  {
    return "afnan/wordcount";
  }

  static const char* value(const ::afnan::wordcount&) { return value(); }
};


// service_traits::MD5Sum< ::afnan::wordcountRequest> should match
// service_traits::MD5Sum< ::afnan::wordcount >
template<>
struct MD5Sum< ::afnan::wordcountRequest>
{
  static const char* value()
  {
    return MD5Sum< ::afnan::wordcount >::value();
  }
  static const char* value(const ::afnan::wordcountRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::afnan::wordcountRequest> should match
// service_traits::DataType< ::afnan::wordcount >
template<>
struct DataType< ::afnan::wordcountRequest>
{
  static const char* value()
  {
    return DataType< ::afnan::wordcount >::value();
  }
  static const char* value(const ::afnan::wordcountRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::afnan::wordcountResponse> should match
// service_traits::MD5Sum< ::afnan::wordcount >
template<>
struct MD5Sum< ::afnan::wordcountResponse>
{
  static const char* value()
  {
    return MD5Sum< ::afnan::wordcount >::value();
  }
  static const char* value(const ::afnan::wordcountResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::afnan::wordcountResponse> should match
// service_traits::DataType< ::afnan::wordcount >
template<>
struct DataType< ::afnan::wordcountResponse>
{
  static const char* value()
  {
    return DataType< ::afnan::wordcount >::value();
  }
  static const char* value(const ::afnan::wordcountResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AFNAN_MESSAGE_WORDCOUNT_H
