// Generated by gencpp from file afnan/wordcountRequest.msg
// DO NOT EDIT!


#ifndef AFNAN_MESSAGE_WORDCOUNTREQUEST_H
#define AFNAN_MESSAGE_WORDCOUNTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace afnan
{
template <class ContainerAllocator>
struct wordcountRequest_
{
  typedef wordcountRequest_<ContainerAllocator> Type;

  wordcountRequest_()
    : mystring()  {
    }
  wordcountRequest_(const ContainerAllocator& _alloc)
    : mystring(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _mystring_type;
  _mystring_type mystring;





  typedef boost::shared_ptr< ::afnan::wordcountRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::afnan::wordcountRequest_<ContainerAllocator> const> ConstPtr;

}; // struct wordcountRequest_

typedef ::afnan::wordcountRequest_<std::allocator<void> > wordcountRequest;

typedef boost::shared_ptr< ::afnan::wordcountRequest > wordcountRequestPtr;
typedef boost::shared_ptr< ::afnan::wordcountRequest const> wordcountRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::afnan::wordcountRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::afnan::wordcountRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::afnan::wordcountRequest_<ContainerAllocator1> & lhs, const ::afnan::wordcountRequest_<ContainerAllocator2> & rhs)
{
  return lhs.mystring == rhs.mystring;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::afnan::wordcountRequest_<ContainerAllocator1> & lhs, const ::afnan::wordcountRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace afnan

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::afnan::wordcountRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::afnan::wordcountRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::afnan::wordcountRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::afnan::wordcountRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::afnan::wordcountRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::afnan::wordcountRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::afnan::wordcountRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e8054fff057e825e73968032a7c26bc8";
  }

  static const char* value(const ::afnan::wordcountRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe8054fff057e825eULL;
  static const uint64_t static_value2 = 0x73968032a7c26bc8ULL;
};

template<class ContainerAllocator>
struct DataType< ::afnan::wordcountRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "afnan/wordcountRequest";
  }

  static const char* value(const ::afnan::wordcountRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::afnan::wordcountRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string mystring\n"
"\n"
;
  }

  static const char* value(const ::afnan::wordcountRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::afnan::wordcountRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mystring);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct wordcountRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::afnan::wordcountRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::afnan::wordcountRequest_<ContainerAllocator>& v)
  {
    s << indent << "mystring: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.mystring);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AFNAN_MESSAGE_WORDCOUNTREQUEST_H
