// Generated by gencpp from file afnan/wordcountResponse.msg
// DO NOT EDIT!


#ifndef AFNAN_MESSAGE_WORDCOUNTRESPONSE_H
#define AFNAN_MESSAGE_WORDCOUNTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace afnan
{
template <class ContainerAllocator>
struct wordcountResponse_
{
  typedef wordcountResponse_<ContainerAllocator> Type;

  wordcountResponse_()
    : count(0)  {
    }
  wordcountResponse_(const ContainerAllocator& _alloc)
    : count(0)  {
  (void)_alloc;
    }



   typedef int32_t _count_type;
  _count_type count;





  typedef boost::shared_ptr< ::afnan::wordcountResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::afnan::wordcountResponse_<ContainerAllocator> const> ConstPtr;

}; // struct wordcountResponse_

typedef ::afnan::wordcountResponse_<std::allocator<void> > wordcountResponse;

typedef boost::shared_ptr< ::afnan::wordcountResponse > wordcountResponsePtr;
typedef boost::shared_ptr< ::afnan::wordcountResponse const> wordcountResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::afnan::wordcountResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::afnan::wordcountResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::afnan::wordcountResponse_<ContainerAllocator1> & lhs, const ::afnan::wordcountResponse_<ContainerAllocator2> & rhs)
{
  return lhs.count == rhs.count;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::afnan::wordcountResponse_<ContainerAllocator1> & lhs, const ::afnan::wordcountResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace afnan

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::afnan::wordcountResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::afnan::wordcountResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::afnan::wordcountResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::afnan::wordcountResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::afnan::wordcountResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::afnan::wordcountResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::afnan::wordcountResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "602d642babe509c7c59f497c23e716a9";
  }

  static const char* value(const ::afnan::wordcountResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x602d642babe509c7ULL;
  static const uint64_t static_value2 = 0xc59f497c23e716a9ULL;
};

template<class ContainerAllocator>
struct DataType< ::afnan::wordcountResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "afnan/wordcountResponse";
  }

  static const char* value(const ::afnan::wordcountResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::afnan::wordcountResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"int32 count\n"
;
  }

  static const char* value(const ::afnan::wordcountResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::afnan::wordcountResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.count);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct wordcountResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::afnan::wordcountResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::afnan::wordcountResponse_<ContainerAllocator>& v)
  {
    s << indent << "count: ";
    Printer<int32_t>::stream(s, indent + "  ", v.count);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AFNAN_MESSAGE_WORDCOUNTRESPONSE_H
